### ISSUE TITLE
Voces planejam continuar o projeto?

### ISSUE THREAD

**Issue by AllanOricil** [marceloatg/vuetning#109]
No momento estou usando LWC design system puro, mas sozinho ele é bem ruim para controlar o estado do componente. Então resolvi procurar na net uma solução pronta e achei a lib de vocês. Queria saber se está estável e se já usaram em algum projeto.

**Comment by marceloatg** [comment]
Olá @AllanOricil , muito obrigado por ter interagido aqui no repositório!

**TL;DR:** O vuetning está estável? Não. Já usaram em algum projeto? Sim. Planejam manter o projeto? Absolutamente sim.

O vuetning nasceu dentro de um projeto comercial ([Blue Bear](https://bluebear.app)) que estou trabalhando no meu tempo livre, como não havia nada na comunidade vue que apresentasse componentes lightning como existe para React, decidi deixar o projeto aberto para justamente ter ajuda da comunidade no desenvolvimento e padronização.

Não considero o projeto estável ainda para uso, principalmente pois existem alguns padrões a serem definidos, tem alguns componentes cujas props vão mudar, vou remover a prop **variant** e substituir por multiplas props booleanas, tal como o vuetify utiliza.

O projeto vai ser mantido sim, por muito tempo, vou desenvolver uma versão ou algo do tipo pro vue 3 futuramente, e toda ajuda é mais que bem vinda no desenvolvimento do vuetning! Sou uma pessoa bem ativa, então vou responder assim que possível, se quiser postar dúvidas, sugestões, pull requests é só mandar que ficarei feliz em trabalhar nesses pontos.

Por motivos de demonstração seguem algumas imagens do Blue Bear hoje, em fase beta fechado utilizando o vuetning:

<img width="1437" alt="screenshot 1" src="https://user-images.githubusercontent.com/3721845/90337771-17d5fe00-dfbb-11ea-842d-003d3d8eac0e.png">
<img width="1437" alt="screenshot 2" src="https://user-images.githubusercontent.com/3721845/90337773-19072b00-dfbb-11ea-9563-7ce5c2ffbd7e.png">
<img width="1437" alt="screenshot 3" src="https://user-images.githubusercontent.com/3721845/90337774-19072b00-dfbb-11ea-9fc2-c58480a3c3f7.png">
<img width="1437" alt="screenshot 4" src="https://user-images.githubusercontent.com/3721845/90337776-199fc180-dfbb-11ea-9887-b61cc6b40ced.png">

PS: Se quiser testar o Blue Bear, podemos conversar sobre em privado, trata-se de várias ferramentas para o desenvolvimento Salesforce, cujo MVP foca em comparação de metadados entre orgs e rápida implantação sem o envolvimento de conjuntos de alteração.

**Comment by AllanOricil** [comment]
Cara, voce teria tempo sobrando pra participar de um projeto comigo? Se der, vamos marcar uma reuniao para eu te apresentar a ideia.

**Comment by marceloatg** [comment]
@marceloatg tempo é um pouco complicado, mas vamos conversar sim, sempre bom compartilhar ideias.
meu email pessoal é marceloatg@outlook.com, manda mensagem lá que eu te passo meus contatos, se quiser conversar hoje mesmo por sinal, hoje estou livre.
