### ISSUE TITLE
Combo box not showing Dropdown Icon [BUG]

### ISSUE THREAD

**Issue by AllanOricil** [marceloatg/vuetning#110]
I added the Combo box and the dropdown icon is not appearing

**Comment by AllanOricil** [comment]
Então, eu fiz funcionar no Nuxt. Mas tive que jogar na pasta "static". O nuxt não conseguiu importar o ".svg" durante o build. Então eu criei uma pasta chamada "assets" dentro da pasta "static" e deu certo.

![image](https://user-images.githubusercontent.com/55927613/90338192-2d98f280-dfbe-11ea-9ca8-6a5c2c669776.png)

Acho que é porque no componente "svg" você ta dando import dinâmico. E se você fizer um import em todo o utility-sprite.svg, e ai no componente você pega o icone que precisamos dependendo das props? Isso faria com que o nuxt importasse o ".svg" da pasta "assets" fazendo com que ele fosse adicionado inline pelo webpack.

**Comment by marceloatg** [comment]
@AllanOricil sory for not provide a documentation at this stage, unfortunately it takes huge amounts of time. You are not seeing the icons probably because there's some misconfiguration with your SLDS, the svg component will look specifically into the public assets folder (root) to get the svgs. I'll edit the readme fiule later to address this issue.

**Comment by marceloatg** [comment]
@AllanOricil eu confesso que estava trabalhando nisso justamente ontem, e desisti porque não consegui de jeito nenhum fazer o vue importar corretamente as sprites svg do SLDS. Seria muito bom ter pelo menos os icones dentro do vuetning, principalmente pra evitar um bug do chrome de exibição de SVG, mas no momento e não consegui fazer. Se você quiser mandar um pull request com a mudança funcionando, vou ficar super feliz. Caso não possa, em algum momento no futuro eu vou voltar a tentar deixar isso interno, pra não ter esse problema.

**Comment by AllanOricil** [comment]
> @AllanOricil sory for not provide a documentation at this stage, unfortunately it takes huge amounts of time. You are not seeing the icons probably because there's some misconfiguration with your SLDS, the svg component will look specifically into the public assets folder (root) to get the svgs. I'll edit the readme fiule later to address this issue.

Esse foi o jeito que eu tentei na primeira vez. Como voce disse, eu usei a pasta "assets" que está no meu "root". No nuxt tudo que ta no assets é usado durante o build pra anexar inline no codigo. 

> @AllanOricil eu confesso que estava trabalhando nisso justamente ontem, e desisti porque não consegui de jeito nenhum fazer o vue importar corretamente as sprites svg do SLDS. Seria muito bom ter pelo menos os icones dentro do vuetning, principalmente pra evitar um bug do chrome de exibição de SVG, mas no momento e não consegui fazer. Se você quiser mandar um pull request com a mudança funcionando, vou ficar super feliz. Caso não possa, em algum momento no futuro eu vou voltar a tentar deixar isso interno, pra não ter esse problema.



> @AllanOricil eu confesso que estava trabalhando nisso justamente ontem, e desisti porque não consegui de jeito nenhum fazer o vue importar corretamente as sprites svg do SLDS. Seria muito bom ter pelo menos os icones dentro do vuetning, principalmente pra evitar um bug do chrome de exibição de SVG, mas no momento e não consegui fazer. Se você quiser mandar um pull request com a mudança funcionando, vou ficar super feliz. Caso não possa, em algum momento no futuro eu vou voltar a tentar deixar isso interno, pra não ter esse problema.

**Comment by AllanOricil** [comment]
> @AllanOricil eu confesso que estava trabalhando nisso justamente ontem, e desisti porque não consegui de jeito nenhum fazer o vue importar corretamente as sprites svg do SLDS. Seria muito bom ter pelo menos os icones dentro do vuetning, principalmente pra evitar um bug do chrome de exibição de SVG, mas no momento e não consegui fazer. Se você quiser mandar um pull request com a mudança funcionando, vou ficar super feliz. Caso não possa, em algum momento no futuro eu vou voltar a tentar deixar isso interno, pra não ter esse problema.

Vou tentar :D
