### ISSUE TITLE
Combo box has options and the dropdown show two items, but the labels are not appearing[BUG]

### ISSUE THREAD

**Issue by AllanOricil** [marceloatg/vuetning#111]
this is my component
```js
<slds-combobox
      v-model="options.gender"
      label="Gender"
      placeholder="Select an Option"
      :options="['Feminine', 'Masculine']"
    ></slds-combobox>
```

When I click the dropdown with two options appear, but they are empty

![image](https://user-images.githubusercontent.com/55927613/90337452-de9c8e80-dfb8-11ea-85a7-36e4cbc08aeb.png)

**Comment by AllanOricil** [comment]
Consegui fazer funcionar

```js
<slds-combobox
      v-model="sobject.gender"
      label="Gender"
      placeholder="Select an Option"
      :options="[
        {
          value: 'Feminine',
          label: 'Feminine',
        },
        {
          value: 'Masculine',
          label: 'Masculine',
        },
      ]"
    ></slds-combobox>
```

Meu erro foi que as options são um objeto

**Comment by marceloatg** [comment]
@AllanOricil isso é algo que vou ajustar ainda, deixar o mais flexível possível, se o usuário quiser passar um array de strings, o componente vai entender, se quiser um array de objetos também.

É um ajuste bem simples, que vai melhorar o componente. Preciso também criar a documentação, porém por tomar muito tempo ainda não pude trabalhar nela.
